const API_URL=window.WORK_LEDGER_CONFIG?.apiUrl?.trim()||'';
const STATUS_OPTIONS=['예정','대기','진행','검수','완료','보류'];
const seed=[
{id:'1',rms:'87036',dates:['2026-09-15'],task:'[DCBGIT-44424] [개인화] 추천 영역 UI 개선 및 운영 반영',status:'완료',category:'플러스탭',hours:{'2026-09-02':1,'2026-09-03':2,'2026-09-04':1.5,'2026-09-07':2,'2026-09-08':3,'2026-09-14':.75}},
{id:'2',rms:'86944',dates:['2026-09-11'],task:'[메인][플러스탭] 9월 콘텐츠 썸네일 및 상세 페이지 교체',status:'완료',category:'메인',hours:{'2026-09-01':2,'2026-09-02':3,'2026-09-09':1,'2026-09-10':2}},
{id:'3',rms:'87081',dates:['2026-09-18'],task:'[DCBGIT-44510] 고객지원 페이지 접근성 개선 요청',status:'진행',category:'공통',hours:{'2026-09-08':1,'2026-09-09':2,'2026-09-10':3,'2026-09-11':2,'2026-09-14':3}},
{id:'4',rms:'87103',dates:['2026-09-22'],task:'[닷컴개발요청SR] 모바일 요금제 랜딩 수정 및 QA',status:'검수',category:'닷컴개발요청SR',hours:{'2026-09-14':2,'2026-09-15':3,'2026-09-16':3,'2026-09-17':1}},
{id:'5',rms:'',dates:['2026-09-25'],task:'[플러스탭] Simple. Lab 9월 월간 리포트 제작',status:'진행',category:'플러스탭',hours:{'2026-09-17':2,'2026-09-18':4,'2026-09-21':3}},
{id:'6',rms:'87145',dates:['2026-09-29'],task:'[공통] GNB 검색 인터랙션 수정',status:'예정',category:'공통',hours:{}},
{id:'7',rms:'86872',dates:['2026-09-04'],task:'[메인] 프로모션 KV 배너 반응형 오류 수정',status:'완료',category:'메인',hours:{'2026-09-01':1,'2026-09-02':2,'2026-09-03':2}},
{id:'8',rms:'87098',dates:['2026-09-24'],task:'[플러스탭] 생일 파티 이벤트 종료 콘텐츠 교체',status:'보류',category:'플러스탭',hours:{'2026-09-11':1,'2026-09-14':2}}
];
let current=new Date(new Date().getFullYear(),new Date().getMonth(),1),tasks=[],selectedDates=[],draggedId=null,saveTimer=null;
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0'),dateKey=(y,m,d)=>`${y}-${pad(m+1)}-${pad(d)}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function showSync(message,type=''){const box=$('#syncBanner');box.className=`sync-banner ${type}`;box.textContent=message}
function normalizeTask(t){const dates=Array.isArray(t.dates)?t.dates:(t.date?[t.date]:[]);return {...t,id:String(t.id),dates:[...new Set(dates.filter(Boolean))].sort(),hours:t.hours||{}}}
async function api(action,payload={}){if(!API_URL)throw new Error('config.js에 Apps Script 웹 앱 URL을 설정해 주세요.');const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});if(!response.ok)throw new Error(`서버 응답 오류 (${response.status})`);const data=await response.json();if(!data.ok)throw new Error(data.error||'요청에 실패했습니다.');return data}
async function loadTasks(){try{const data=await api('load');tasks=(data.tasks?.length?data.tasks:seed).map(normalizeTask);render();showSync(data.tasks?.length?'서버 데이터를 불러왔습니다.':'서버가 비어 있어 예시 데이터를 표시합니다. 첫 변경 시 저장됩니다.','success')}catch(error){tasks=seed.map(normalizeTask);render();showSync(error.message,'error')}}
function queueSave(){clearTimeout(saveTimer);showSync('변경 내용을 저장하는 중입니다.');saveTimer=setTimeout(saveAll,350)}
async function saveAll(){try{await api('save',{tasks});showSync('모든 변경 내용이 저장되었습니다.','success');return true}catch(error){showSync(`저장 실패: ${error.message}`,'error');return false}}
function render(){const y=current.getFullYear(),m=current.getMonth(),days=new Date(y,m+1,0).getDate();$('#monthLabel').textContent=`${y}년 ${m+1}월`;let heads='';for(let d=1;d<=days;d++){const dow=new Date(y,m,d).getDay(),w=['일','월','화','수','목','금','토'][dow];heads+=`<th class="day ${dow===0||dow===6?'weekend':''}">${d}<small>${w}</small></th>`}$('#ledgerHead').innerHTML=`<tr><th class="month-head" colspan="6">업무 정보</th><th class="month-head" colspan="${days}">${y}년 ${m+1}월 일별 작업시간</th><th class="month-head">합계</th></tr><tr><th class="fixed col-drag">순서</th><th class="fixed col-no">NO</th><th class="fixed col-rms">RMS</th><th class="fixed col-date">반영일</th><th class="fixed col-task">업무명</th><th class="fixed col-status">진행현황</th>${heads}<th>합계</th></tr>`;
const q=$('#search').value.toLowerCase(),status=$('#statusFilter').value,cat=$('#categoryFilter').value,filtered=tasks.filter(t=>(!q||`${t.rms} ${t.task}`.toLowerCase().includes(q))&&(!status||t.status===status)&&(!cat||t.category===cat));$('#visibleCount').textContent=`${filtered.length}개`;$('#empty').style.display=filtered.length?'none':'block';
$('#ledgerBody').innerHTML=filtered.map((t,i)=>{let cells='',total=0;for(let d=1;d<=days;d++){const key=dateKey(y,m,d),val=t.hours[key]??'',dow=new Date(y,m,d).getDay();total+=Number(val)||0;cells+=`<td class="day ${dow===0||dow===6?'weekend':''}"><input class="hour-input" inputmode="decimal" value="${esc(val)}" data-id="${esc(t.id)}" data-date="${key}" aria-label="${m+1}월 ${d}일 작업시간"></td>`}const dates=t.dates.length?t.dates.map(d=>`<span class="date-badge">${esc(d.slice(5).replace('-','/'))}</span>`).join(''):'-';return `<tr draggable="true" data-row-id="${esc(t.id)}"><td class="fixed col-drag"><button class="drag-handle" type="button" aria-label="${i+1}번 업무 순서 이동">⠿</button></td><td class="fixed col-no">${i+1}</td><td class="fixed col-rms">${t.rms?`<a class="rms-link" href="http://210.108.138.187/redmine/issues/${esc(t.rms)}" target="_blank" rel="noopener">${esc(t.rms)}</a>`:'-'}</td><td class="fixed col-date"><div class="date-list">${dates}</div></td><td class="fixed col-task"><div class="task-name" title="${esc(t.task)}">${esc(t.task)}</div></td><td class="fixed col-status"><select class="status-select status-${esc(t.status)}" data-status="${esc(t.id)}">${STATUS_OPTIONS.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></td>${cells}<td class="total-cell">${total||'-'}</td></tr>`}).join('')}
function renderDateChips(){const box=$('#dateChips');box.innerHTML=selectedDates.length?selectedDates.map(d=>`<span class="date-chip">${esc(d)}<button type="button" data-remove-date="${esc(d)}" aria-label="${esc(d)} 삭제">×</button></span>`).join(''):'<span style="color:var(--muted);font-weight:400">반영일을 1개 이상 추가하세요.</span>'}
$('#prevMonth').onclick=()=>{current.setMonth(current.getMonth()-1);render()};$('#nextMonth').onclick=()=>{current.setMonth(current.getMonth()+1);render()};['search','statusFilter','categoryFilter'].forEach(id=>$('#'+id).addEventListener('input',render));
$('#ledgerBody').addEventListener('change',e=>{const hour=e.target.closest('.hour-input'),status=e.target.closest('[data-status]');if(hour){const t=tasks.find(x=>x.id===hour.dataset.id),v=hour.value.trim();if(v==='')delete t.hours[hour.dataset.date];else t.hours[hour.dataset.date]=Math.max(0,Number(v)||0)}if(status)tasks.find(x=>x.id===status.dataset.status).status=status.value;queueSave();render()});
$('#ledgerBody').addEventListener('dragstart',e=>{const row=e.target.closest('[data-row-id]');if(!row)return;draggedId=row.dataset.rowId;row.classList.add('dragging');e.dataTransfer.effectAllowed='move'});$('#ledgerBody').addEventListener('dragover',e=>{const row=e.target.closest('[data-row-id]');if(!row||row.dataset.rowId===draggedId)return;e.preventDefault();document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'));row.classList.add('drag-over')});$('#ledgerBody').addEventListener('drop',e=>{const target=e.target.closest('[data-row-id]');if(!target||!draggedId||target.dataset.rowId===draggedId)return;e.preventDefault();const from=tasks.findIndex(t=>t.id===draggedId),to=tasks.findIndex(t=>t.id===target.dataset.rowId),moved=tasks.splice(from,1)[0];tasks.splice(to,0,moved);queueSave();render()});$('#ledgerBody').addEventListener('dragend',()=>{draggedId=null;document.querySelectorAll('.dragging,.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'))});
$('#addButton').onclick=()=>{selectedDates=[];renderDateChips();$('#taskDialog').showModal()};$('#addDate').onclick=()=>{const value=$('#releaseDate').value;if(value&&!selectedDates.includes(value)){selectedDates.push(value);selectedDates.sort();renderDateChips()}$('#releaseDate').value=''};$('#dateChips').onclick=e=>{const button=e.target.closest('[data-remove-date]');if(button){selectedDates=selectedDates.filter(d=>d!==button.dataset.removeDate);renderDateChips()}};
$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();if(!selectedDates.length){showSync('업무 등록 전에 반영일을 1개 이상 추가해 주세요.','error');return}const f=new FormData(e.target),newTask={id:crypto.randomUUID?.()||String(Date.now()),rms:String(f.get('rms')||''),dates:[...selectedDates],task:String(f.get('task')),status:String(f.get('status')),category:String(f.get('category')),hours:{}};tasks.push(newTask);render();if(await saveAll()){e.target.reset();selectedDates=[];$('#taskDialog').close()}else tasks=tasks.filter(t=>t.id!==newTask.id)});
loadTasks();
