const API_URL=window.WORK_LEDGER_CONFIG?.apiUrl?.trim()||'';
const STORAGE_KEY='work-ledger-tasks';
const STATUS_OPTIONS=['예정','보류','진행','검수','대기','완료'];
const STATUS_CLASSES={'예정':'planned','보류':'on-hold','진행':'in-progress','검수':'review','대기':'waiting','완료':'completed'};
const LEAVE_TYPES={annual:{label:'연차',days:1},half:{label:'반차',days:.5},quarter:{label:'반반차',days:.25}};
const LEAVE_CALENDAR_ID='__leave_calendar__';
const MIN_MONTH=new Date(2026,0,1);
let current=new Date(new Date().getFullYear(),new Date().getMonth(),1),tasks=[],leaveDays={},holidays=new Set(),loadedHolidayYears=new Set(),selectedDates=[],editingTaskId=null,editingLeaveDate='',draggedId=null,reorderMode=false,selectedWeek=0,saveTimer=null;
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0'),dateKey=(y,m,d)=>`${y}-${pad(m+1)}-${pad(d)}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function issueUrl(value){const entry=String(value||'').trim();if(/^DCBGIT-\d+$/i.test(entry))return `https://lgdigitalcommerce.atlassian.net/browse/${entry.toUpperCase()}`;if(/^\d+$/.test(entry))return `http://kms-redmine.medialog.co.kr/redmine/issues/${entry}`;if(/^https?:\/\//i.test(entry))return entry;return ''}
function showSync(message,type=''){const box=$('#syncBanner');box.className=`sync-banner ${type}`;box.textContent=message}
function normalizeTask(t){const dates=Array.isArray(t.dates)?t.dates:(t.date?[t.date]:[]);return {...t,id:String(t.id),dates:[...new Set(dates.filter(Boolean))].sort(),hours:t.hours||{},leaves:t.leaves||{}}}
async function api(action,payload={}){if(!API_URL)throw new Error('config.js에 Apps Script 웹 앱 URL을 설정해 주세요.');const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});if(!response.ok)throw new Error(`서버 응답 오류 (${response.status})`);const data=await response.json();if(!data.ok)throw new Error(data.error||'요청에 실패했습니다.');return data}
async function loadTasks(){try{const data=await api('load'),loaded=data.tasks||[],calendar=loaded.find(task=>task.id===LEAVE_CALENDAR_ID||task._type==='leave-calendar');leaveDays=calendar?.leaves||{};holidays=new Set((data.holidays||[]).filter(date=>/^\d{4}-\d{2}-\d{2}$/.test(date)));loadedHolidayYears=new Set([current.getFullYear()]);tasks=loaded.filter(task=>task!==calendar).map(normalizeTask);localStorage.removeItem(STORAGE_KEY);selectTodayWeek();render();showSync(tasks.length?'서버 데이터를 불러왔습니다.':'등록된 업무가 없습니다.','success')}catch(error){tasks=[];leaveDays={};holidays=new Set();loadedHolidayYears=new Set();render();showSync(error.message,'error')}}
async function ensureHolidayYear(year){if(loadedHolidayYears.has(year))return;try{const data=await api('holidays',{year});(data.holidays||[]).forEach(date=>holidays.add(date));loadedHolidayYears.add(year)}catch(error){showSync(`공휴일 조회 실패: ${error.message}`,'error')}}
function queueSave(){clearTimeout(saveTimer);showSync('변경 내용을 저장하는 중입니다.');saveTimer=setTimeout(saveAll,350)}
async function saveAll(){try{await api('save',{tasks:[...tasks,{id:LEAVE_CALENDAR_ID,_type:'leave-calendar',leaves:leaveDays}]});showSync('모든 변경 내용이 저장되었습니다.','success');return true}catch(error){showSync(`저장 실패: ${error.message}`,'error');return false}}
function syncFixedColumns(){const headers=[...document.querySelectorAll('.ledger-head-fields > .fixed')];let offset=0;headers.forEach((header,index)=>{document.querySelectorAll(`.ledger-head-fields > :nth-child(${index+1}), #ledgerBody > tr > :nth-child(${index+1})`).forEach(cell=>cell.style.insetInlineStart=`${offset}px`);offset+=header.getBoundingClientRect().width})}
function isWorkDay(y,m,d){const dow=new Date(y,m,d).getDay();return dow!==0&&dow!==6&&!holidays.has(dateKey(y,m,d))}
function reportDays(y,m,days){const cutoffs=[];for(let d=1;d<=days;d++)if(new Date(y,m,d).getDay()===5)cutoffs.push(d);if(!cutoffs.includes(days))cutoffs.push(days);const reports=[];let periodStart=1;for(const cutoff of cutoffs){let last=cutoff;while(last>=periodStart&&!isWorkDay(y,m,last))last--;if(last>=periodStart&&!reports.includes(last))reports.push(last);periodStart=cutoff+1}return reports.length?reports:[days]}
function selectTodayWeek(){const today=new Date();if(current.getFullYear()!==today.getFullYear()||current.getMonth()!==today.getMonth())return;const reports=reportDays(current.getFullYear(),current.getMonth(),new Date(current.getFullYear(),current.getMonth()+1,0).getDate()),index=reports.findIndex(day=>today.getDate()<=day);selectedWeek=index>=0?index:Math.max(0,reports.length-1)}
function displayTotal(value){const converted=value/8,rounded=Math.round(converted*1000)/1000;return rounded||'-'}
function leaveInfo(value){if(value&&typeof value==='object')return {type:LEAVE_TYPES[value.type]?value.type:'annual',substitute:Boolean(value.substitute)};if(value==='substitute')return {type:'annual',substitute:true};return {type:LEAVE_TYPES[value]?value:'annual',substitute:false}}
function renderPeriodControls(filtered,y,m,visibleDays,reports,weekEnd){$('#weekSelect').innerHTML=reports.map((day,index)=>{const start=index?reports[index-1]+1:1;return `<option value="${index}">${index+1}주차 (${m+1}/${start}~${m+1}/${day})</option>`}).join('');$('#weekSelect').value=String(selectedWeek);const daily={};visibleDays.forEach(day=>daily[day]=0);filtered.forEach(task=>visibleDays.forEach(day=>daily[day]+=Number(task.hours[dateKey(y,m,day)])||0));const today=dateKey(new Date().getFullYear(),new Date().getMonth(),new Date().getDate()),dailyCells=visibleDays.map(day=>{const key=dateKey(y,m,day),value=leaveDays[key],leave=value?leaveInfo(value).type:'',isToday=key===today;return `<td class="day${leave?` leave-${leave}`:''}${isToday?' today':''}" data-date="${key}">${displayTotal(daily[day])}</td>`}),weeklyTotal=visibleDays.reduce((total,day)=>total+daily[day],0),weeklyCells=visibleDays.map(day=>{const value=leaveDays[dateKey(y,m,day)],leave=value?leaveInfo(value).type:'',key=dateKey(y,m,day),classes=[day===weekEnd?'weekly-total report-day':'','day',leave?`leave-${leave}`:'',key===today?'today':''].filter(Boolean).join(' ');return `<td class="${classes}" data-date="${key}">${day===weekEnd?displayTotal(weeklyTotal):''}</td>`});$('#ledgerFoot').innerHTML=`<tr class="daily-summary"><th class="summary-label" colspan="5">일일 합계</th>${dailyCells.join('')}<td class="total-cell">${displayTotal(weeklyTotal)}</td></tr><tr class="weekly-summary"><th class="summary-label" colspan="5">주간 합계</th>${weeklyCells.join('')}<td class="total-cell">${displayTotal(weeklyTotal)}</td></tr>`}
function render(){const y=current.getFullYear(),m=current.getMonth(),days=new Date(y,m+1,0).getDate(),reports=reportDays(y,m,days);selectedWeek=Math.min(selectedWeek,reports.length-1);const weekStart=selectedWeek?reports[selectedWeek-1]+1:1,weekEnd=reports[selectedWeek],visibleDays=[];for(let d=weekStart;d<=weekEnd;d++){const dow=new Date(y,m,d).getDay();if(dow!==0&&dow!==6&&!holidays.has(dateKey(y,m,d)))visibleDays.push(d)}$('#monthLabel').textContent=`${y}년 ${m+1}월`;$('#prevMonth').disabled=current<=MIN_MONTH;$('#ledgerColumns').innerHTML=`<col class="col-no"><col class="col-rms"><col class="col-task"><col class="col-date"><col class="col-status">${visibleDays.map(()=>'<col class="day-column">').join('')}<col class="col-total">`;const today=dateKey(new Date().getFullYear(),new Date().getMonth(),new Date().getDate());let heads='';for(const d of visibleDays){const key=dateKey(y,m,d),dow=new Date(y,m,d).getDay(),w=['일','월','화','수','목','금','토'][dow],value=leaveDays[key],leave=value?leaveInfo(value).type:'',isToday=key===today;heads+=`<th class="day${leave?` leave-${leave}`:''}${isToday?' today':''}" data-day="${d}">${d}<small>${w}</small></th>`}$('#ledgerHead').innerHTML=`<tr class="ledger-head-months"><th class="month-head info-head" colspan="5">업무 정보</th><th class="month-head" colspan="${visibleDays.length}">${y}년 ${m+1}월 ${selectedWeek+1}주차</th><th class="month-head">합계</th></tr><tr class="ledger-head-fields"><th class="fixed col-no">NO</th><th class="fixed col-rms">RMS, Jira</th><th class="fixed col-task">업무명</th><th class="fixed col-date">반영일</th><th class="fixed col-status">진행현황</th>${heads}<th>합계</th></tr>`;
const q=$('#search').value.toLowerCase(),status=$('#statusFilter').value,cat=$('#categoryFilter').value,filtered=tasks.filter(t=>(!q||`${t.rms} ${t.task}`.toLowerCase().includes(q))&&(!status||t.status===status)&&(!cat||t.category===cat));$('#visibleCount').textContent=`${filtered.length}개`;$('#empty').style.display=filtered.length?'none':'block';
$('#ledgerBody').classList.toggle('reorder-mode',reorderMode);$('#ledgerBody').innerHTML=filtered.map((t,i)=>{let cells='',total=0;for(const d of visibleDays){const key=dateKey(y,m,d),val=t.hours[key]??'',leaveValue=leaveDays[key],leave=leaveValue?leaveInfo(leaveValue):null,leaveLabel=leave?`${LEAVE_TYPES[leave.type].label}${leave.substitute?' · 대체휴가':''}`:'',isToday=key===today;total+=Number(val)||0;cells+=`<td class="day${leave?` leave-${leave.type}`:''}${isToday?' today':''}"><input class="hour-input${leave?` leave-${leave.type}`:''}" type="number" min="0" step="1" value="${esc(val)}" data-id="${esc(t.id)}" data-date="${key}" aria-label="${m+1}월 ${d}일 작업 시간${leaveLabel?`, ${leaveLabel}`:''}" title="${leaveLabel}"></td>`}const dates=t.dates.length?t.dates.map(d=>`<span class="date-badge">${esc(d.slice(5).replace('-','/'))}</span>`).join(''):'-',link=issueUrl(t.rms);return `<tr class="row-status-${STATUS_CLASSES[t.status]||'unknown'}" draggable="${reorderMode}" data-row-id="${esc(t.id)}"><td class="fixed col-no">${i+1}</td><td class="fixed col-rms">${link?`<a class="rms-link" href="${esc(link)}" target="_blank" rel="noopener">${esc(t.rms)}</a>`:(esc(t.rms)||'-')}</td><td class="fixed col-task"><button class="task-name task-edit" type="button" data-edit-id="${esc(t.id)}" title="업무 수정: ${esc(t.task)}">${esc(t.task)}</button></td><td class="fixed col-date"><div class="date-list">${dates}</div></td><td class="fixed col-status"><select class="status-select status-${STATUS_CLASSES[t.status]||'unknown'}" data-status="${esc(t.id)}">${STATUS_OPTIONS.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></td>${cells}<td class="total-cell">${displayTotal(total)}</td></tr>`}).join('');renderPeriodControls(filtered,y,m,visibleDays,reports,weekEnd);syncFixedColumns()}
function renderDateChips(){const box=$('#dateChips');box.innerHTML=selectedDates.length?selectedDates.map(d=>`<span class="date-chip">${esc(d)}<button type="button" data-remove-date="${esc(d)}" aria-label="${esc(d)} 삭제">×</button></span>`).join(''):'<span style="color:var(--muted);font-weight:400">반영일을 1개 이상 추가하세요.</span>'}
$('#prevMonth').onclick=async()=>{if(current<=MIN_MONTH)return;current.setMonth(current.getMonth()-1);selectedWeek=0;await ensureHolidayYear(current.getFullYear());render()};$('#nextMonth').onclick=async()=>{current.setMonth(current.getMonth()+1);selectedWeek=0;await ensureHolidayYear(current.getFullYear());render()};$('#weekSelect').addEventListener('change',e=>{selectedWeek=Number(e.target.value);render()});['search','statusFilter','categoryFilter'].forEach(id=>$('#'+id).addEventListener('input',render));
function applyStatusState(status){const statusClass=STATUS_CLASSES[status.value]||'unknown',task=tasks.find(item=>item.id===status.dataset.status),row=status.closest('[data-row-id]');if(task)task.status=status.value;status.className=`status-select status-${statusClass}`;if(row){row.classList.remove(...Object.values(STATUS_CLASSES).map(value=>`row-status-${value}`),'row-status-unknown');row.classList.add(`row-status-${statusClass}`)}}
function applyHourValue(hour){const task=tasks.find(item=>item.id===hour.dataset.id),value=hour.value.trim();if(!task)return;if(value==='')delete task.hours[hour.dataset.date];else task.hours[hour.dataset.date]=Math.max(0,Number(value)||0)}
function updateVisibleTotals(){const dailyTotals=new Map();let weeklyTotal=0;document.querySelectorAll('#ledgerBody tr[data-row-id]').forEach(row=>{let rowTotal=0;row.querySelectorAll('.hour-input').forEach(input=>{const value=Number(input.value)||0;rowTotal+=value;dailyTotals.set(input.dataset.date,(dailyTotals.get(input.dataset.date)||0)+value)});const totalCell=row.querySelector('.total-cell');if(totalCell)totalCell.textContent=displayTotal(rowTotal);weeklyTotal+=rowTotal});document.querySelectorAll('#ledgerFoot .daily-summary td.day[data-date]').forEach(cell=>cell.textContent=displayTotal(dailyTotals.get(cell.dataset.date)||0));document.querySelectorAll('#ledgerFoot .weekly-summary td.day').forEach(cell=>cell.textContent=cell.classList.contains('report-day')?displayTotal(weeklyTotal):'');document.querySelectorAll('#ledgerFoot .total-cell').forEach(cell=>cell.textContent=displayTotal(weeklyTotal))}
$('#ledgerBody').addEventListener('input',e=>{const hour=e.target.closest('.hour-input'),status=e.target.closest('[data-status]');if(hour){applyHourValue(hour);updateVisibleTotals();queueSave()}if(status)applyStatusState(status)});
$('#ledgerBody').addEventListener('change',e=>{const hour=e.target.closest('.hour-input'),status=e.target.closest('[data-status]');if(hour){applyHourValue(hour);updateVisibleTotals();clearTimeout(saveTimer);saveTimer=null;saveAll()}if(status){applyStatusState(status);queueSave();render()}});
function renderLeaveList(){const entries=Object.entries(leaveDays).sort(([a],[b])=>b.localeCompare(a)),total=entries.reduce((sum,[,value])=>sum+LEAVE_TYPES[leaveInfo(value).type].days,0),excludingSubstitute=entries.reduce((sum,[,value])=>{const leave=leaveInfo(value);return sum+(leave.substitute?0:LEAVE_TYPES[leave.type].days)},0);$('#leaveList').innerHTML=entries.length?entries.map(([date,value])=>{const leave=leaveInfo(value),label=`${LEAVE_TYPES[leave.type].label}${leave.substitute?' · 대체휴가':''}`;return `<button class="leave-list-item leave-${leave.type}${date===editingLeaveDate?' active':''}" type="button" data-edit-leave="${esc(date)}"><span>${esc(date)}</span><span>${esc(label)}</span></button>`}).join(''):'<div class="leave-list-empty">등록된 휴가가 없습니다.</div>';$('#leaveTotalExcludingSubstitute').textContent=`${Math.round(excludingSubstitute*100)/100}일`;$('#leaveTotal').textContent=`${Math.round(total*100)/100}일`}
function resetLeaveForm(){const form=$('#leaveForm'),today=new Date(),sameMonth=today.getFullYear()===current.getFullYear()&&today.getMonth()===current.getMonth();editingLeaveDate='';form.reset();form.elements.leaveDate.value=dateKey(current.getFullYear(),current.getMonth(),sameMonth?today.getDate():1);$('#deleteLeaveButton').hidden=true;$('#saveLeaveButton').textContent='등록';renderLeaveList()}
$('#leaveButton').onclick=()=>{resetLeaveForm();$('#leaveDialog').showModal()};
document.querySelectorAll('[data-leave-dialog-close]').forEach(button=>button.addEventListener('click',()=>$('#leaveDialog').close()));
$('#leaveList').addEventListener('click',e=>{const button=e.target.closest('[data-edit-leave]');if(!button)return;editingLeaveDate=button.dataset.editLeave;const form=$('#leaveForm'),leave=leaveInfo(leaveDays[editingLeaveDate]);form.elements.leaveDate.value=editingLeaveDate;form.elements.leaveType.value=leave.type;form.elements.isSubstitute.checked=leave.substitute;$('#deleteLeaveButton').hidden=false;$('#saveLeaveButton').textContent='수정';renderLeaveList()});
$('#leaveForm').addEventListener('submit',e=>{e.preventDefault();const formData=new FormData(e.target),leaveType=String(formData.get('leaveType')||'annual'),isSubstitute=formData.has('isSubstitute'),leaveDate=String(formData.get('leaveDate')||'');if(!leaveDate)return;const [year,month,day]=leaveDate.split('-').map(Number),dayOfWeek=new Date(year,month-1,day).getDay();if(dayOfWeek===0||dayOfWeek===6){showSync('주말은 업무표에 표시되지 않습니다. 평일을 선택해 주세요.','error');return}if(editingLeaveDate&&editingLeaveDate!==leaveDate)delete leaveDays[editingLeaveDate];leaveDays[leaveDate]={type:leaveType,substitute:isSubstitute};current=new Date(year,month-1,1);const days=new Date(year,month,0).getDate(),reports=reportDays(year,month-1,days);selectedWeek=Math.max(0,reports.findIndex(reportDay=>day<=reportDay));queueSave();render();resetLeaveForm();showSync(`${leaveDate} ${LEAVE_TYPES[leaveType].label}${isSubstitute?' · 대체휴가':''} 배경색을 저장하는 중입니다.`)});
$('#deleteLeaveButton').onclick=()=>{if(!editingLeaveDate)return;const leave=leaveInfo(leaveDays[editingLeaveDate]),label=`${LEAVE_TYPES[leave.type].label}${leave.substitute?' · 대체휴가':''}`;if(!confirm(`${editingLeaveDate} ${label}를 삭제하시겠습니까?`))return;delete leaveDays[editingLeaveDate];queueSave();render();resetLeaveForm();showSync('휴가 표시를 삭제하고 있습니다.')};
$('#reorderButton').onclick=()=>{reorderMode=!reorderMode;$('#reorderButton').textContent=reorderMode?'순서 변경 완료':'순서 변경';$('#reorderButton').classList.toggle('active',reorderMode);render()};
$('#ledgerBody').addEventListener('dragstart',e=>{if(!reorderMode)return;const row=e.target.closest('[data-row-id]');if(!row)return;draggedId=row.dataset.rowId;row.classList.add('dragging');e.dataTransfer.effectAllowed='move'});
$('#ledgerBody').addEventListener('dragover',e=>{if(!reorderMode)return;const row=e.target.closest('[data-row-id]');if(!row||row.dataset.rowId===draggedId)return;e.preventDefault();document.querySelectorAll('.drag-over').forEach(item=>item.classList.remove('drag-over'));row.classList.add('drag-over')});
$('#ledgerBody').addEventListener('drop',e=>{if(!reorderMode)return;const target=e.target.closest('[data-row-id]');if(!target||!draggedId||target.dataset.rowId===draggedId)return;e.preventDefault();const from=tasks.findIndex(task=>task.id===draggedId),to=tasks.findIndex(task=>task.id===target.dataset.rowId),moved=tasks.splice(from,1)[0];tasks.splice(to,0,moved);document.querySelectorAll('.drag-over').forEach(item=>item.classList.remove('drag-over'));queueSave();render()});
$('#ledgerBody').addEventListener('dragend',()=>{draggedId=null;document.querySelectorAll('.dragging,.drag-over').forEach(item=>item.classList.remove('dragging','drag-over'))});
function openTaskDialog(task=null){const form=$('#taskForm');form.reset();editingTaskId=task?.id||null;selectedDates=task?[...task.dates]:[];form.elements.rms.value=task?.rms||'';form.elements.task.value=task?.task||'';if(task){form.elements.status.value=task.status;form.elements.category.value=task.category}$('.dialog-head h2').textContent=task?'업무 수정':'새 업무 등록';$('.dialog-actions .primary').textContent=task?'수정':'등록';$('#deleteButton').hidden=!task;renderDateChips();$('#taskDialog').showModal()}
$('#addButton').onclick=()=>openTaskDialog();$('#addDate').onclick=()=>{const value=$('#releaseDate').value;if(value&&!selectedDates.includes(value)){selectedDates.push(value);selectedDates.sort();renderDateChips()}$('#releaseDate').value=''};$('#dateChips').onclick=e=>{const button=e.target.closest('[data-remove-date]');if(button){selectedDates=selectedDates.filter(d=>d!==button.dataset.removeDate);renderDateChips()}};
$('#ledgerBody').addEventListener('click',e=>{const button=e.target.closest('[data-edit-id]');if(button)openTaskDialog(tasks.find(task=>task.id===button.dataset.editId))});
document.querySelectorAll('[data-dialog-close]').forEach(button=>button.addEventListener('click',()=>$('#taskDialog').close()));
$('#deleteButton').onclick=async()=>{const index=tasks.findIndex(task=>task.id===editingTaskId);if(index<0)return;const removed=tasks[index];if(!confirm(`「${removed.task}」 업무를 삭제하시겠습니까?`))return;tasks.splice(index,1);editingTaskId=null;selectedDates=[];render();$('#taskDialog').close();if(!(await saveAll())){tasks.splice(index,0,removed);render()}};
$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();if(!selectedDates.length){showSync('업무 등록 전에 반영일을 1개 이상 추가해 주세요.','error');return}const f=new FormData(e.target),index=tasks.findIndex(task=>task.id===editingTaskId),previous=index>=0?{...tasks[index],dates:[...tasks[index].dates],hours:{...tasks[index].hours},leaves:{...tasks[index].leaves}}:null,taskData={id:editingTaskId||crypto.randomUUID?.()||String(Date.now()),rms:String(f.get('rms')||''),dates:[...selectedDates],task:String(f.get('task')),status:String(f.get('status')),category:String(f.get('category')),hours:previous?.hours||{},leaves:previous?.leaves||{}};if(index>=0)tasks[index]=taskData;else tasks.push(taskData);render();e.target.reset();selectedDates=[];editingTaskId=null;$('#taskDialog').close();if(!(await saveAll())){if(index>=0)tasks[index]=previous;else tasks=tasks.filter(task=>task.id!==taskData.id);render()}});
loadTasks();
window.addEventListener('resize',syncFixedColumns);
