const DATA_SHEET = '웹앱_업무데이터';
const HOLIDAY_API_URL = 'https://date.nager.at/api/v3/PublicHolidays/';
function doGet(){return jsonResponse(loadPayload())}
function doPost(e){try{const r=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(r.action==='load')return jsonResponse(loadPayload());if(r.action==='holidays')return jsonResponse({ok:true,holidays:getHolidays(r.year)});if(r.action==='save')return jsonResponse(savePayload(r.tasks));return jsonResponse({ok:false,error:'지원하지 않는 요청입니다.'})}catch(error){return jsonResponse({ok:false,error:error.message})}}
function loadPayload(){const s=getDataSheet(),json=s.getRange('A2').getValue();return {ok:true,tasks:json?JSON.parse(json):[],holidays:getHolidays(new Date().getFullYear()),updatedAt:s.getRange('B2').getValue()||''}}
function getHolidays(year){const targetYear=Number(year)||new Date().getFullYear();if(targetYear<2026||targetYear>2100)throw new Error('조회할 연도가 올바르지 않습니다.');const response=UrlFetchApp.fetch(HOLIDAY_API_URL+targetYear+'/KR',{muteHttpExceptions:true,headers:{Accept:'application/json'}});if(response.getResponseCode()!==200)throw new Error('대한민국 공휴일 API 조회에 실패했습니다. ('+response.getResponseCode()+')');const holidays=JSON.parse(response.getContentText());return [...new Set(holidays.map(item=>item.date).filter(date=>/^\d{4}-\d{2}-\d{2}$/.test(date)))].sort()}
function savePayload(tasks){if(!Array.isArray(tasks))throw new Error('업무 데이터 형식이 올바르지 않습니다.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const s=getDataSheet(),updatedAt=new Date().toISOString();s.getRange('A2:B2').setValues([[JSON.stringify(tasks),updatedAt]]);SpreadsheetApp.flush();return {ok:true,updatedAt}}finally{lock.releaseLock()}}
function getDataSheet(){const book=SpreadsheetApp.getActiveSpreadsheet();let sheet=book.getSheetByName(DATA_SHEET);if(!sheet){sheet=book.insertSheet(DATA_SHEET);sheet.getRange('A1:B1').setValues([['업무 데이터(JSON)','최종 저장 시각']]);sheet.hideSheet()}return sheet}
function jsonResponse(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON)}
